### PR TITLE
fix: update deps and env var

### LINKED ISSUE #25: Fix typo in staging secret name
Maybe let's uniformize secrets's content

https://github.com/graasp/graasp-account/blob/0749ae42125524146d3b1c8352447fe05fd47268/.github/workflows/deploy-stage.yml#L52C43-L52C83

### PR DESCRIPTION
**Pull request by spaenleh**
- fix: update deps
- fix: update readme
- fix #25

### CODE REVIEW

File: src/components/common/UserSwitchWrapper.tsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ const UserSwitchWrapper = ({ ButtonContent }: Props): JSX.Element => {
       renderAvatar={renderAvatar}
       profilePath={HOME_PATH}
       redirectPath={GRAASP_AUTH_HOST}
+      userMenuItems={[]}
```
Comment (spaenleh) [inline src/components/common/UserSwitchWrapper.tsx:30]: Ideally this props would be optional so we do not have to set it if we do not need it.

**Review by LinaYahya — APPROVED** [review]
