### PR TITLE
fix: fix platform mobile colors

### LINKED ISSUE #170: mobile platform switch has wrong colors

### PR DESCRIPTION
**Pull request by pyphilia**
Screenshot 2024-03-22 at 16 04 32

close #170

### CODE REVIEW

File: src/components/layout/Header.tsx [hunk 1]
```diff
@@ -67,6 +76,9 @@ const Header = ({ isMenuOpen, toggleMenu }: Props): JSX.Element => {
     [Platform.Analytics]: {
       ...getNavigationEvents(Platform.Analytics),
     },
+    weifjo: {
```
Comment (spaenleh) [inline src/components/layout/Header.tsx:79]: What ??

**Review by spaenleh — CHANGES_REQUESTED** [review]
Looks good, but I am not sure I understand what the `weifjo` means ...

**Review by spaenleh — APPROVED** [review]
